def O (0,0,0) % origo
def dx 7
def dy dx
def dz dx

def axes {
    % draw the axes
    def ax (dx,0,0)
    def ay (0,dy,0)
    def az (0,0,dz)
    line[arrows=<->,line width=.4pt](ax)(O)(ay)
    line[arrows=->,line width=.4pt](O)(az)

    % repeat dotted as an overlay to hint at the hidden lines
    % line[lay=over,line style=dotted,line width=.4pt](ax)(O)(ay)
    % line[lay=over,line style=dotted,line width=.4pt](O)(az)

    % annote axes
    special |\path #1 node[above] {$z$}
                   #2 node[right] {$x$}
                   #3 node[right] {$y$};|(az)(ax)(ay)
}

% octant
def octR put{translate([-1.0,0,0])}{
    def n 1   
  sweep[fill=red!20, fill opacity=0.3, cull=false]
        {n,translate([0,n,0])}
    sweep[fill=red!20, fill opacity=0.3, cull=false]
        {n, translate([n,0,0])}line(1,0,0)(1,0,1)
}

def octB put{translate([-1.0,0,0])}{
    def n 1   
  sweep[fill=blue!20, fill opacity=0.6, cull=false]
        {n,translate([0,n,0])}
    sweep[fill=blue!20, fill opacity=0.6, cull=false]
        {n, translate([n,0,0])}line(1,0,0)(1,0,1)
}

def octG put{translate([-1.0,0,0])}{
    def n 1   
  sweep[fill=green!20, fill opacity=0.8, cull=false]
        {n,translate([0,n,0])}
    sweep[fill=green!20, fill opacity=0.8, cull=false]
        {n, translate([n,0,0])}line(1,0,0)(1,0,1)
}


def sphere put{rotate(90,[0,1,0])}{
   def n_faces 8
   sweep[fill=red, line width= 0.1pt] { n_faces, rotate(360/n_faces, [1,0,0])}
       sweep {n_faces, rotate(360/n_faces)}(0,1)
}

def hanging put{rotate(90,[0,1,0])}{
   def n_faces 8
   sweep[fill=gray, line width= 0.1pt] { n_faces, rotate(360/n_faces, [1,0,0])}
       sweep {n_faces, rotate(360/n_faces)}(0,1)
}

def octScene {

  % Octants ...
  
  put { scale(4) } {octB}
  % put { scale(4) then translate ([4,0,0]) } {octB}
  % smaller 
  put { scale(2) then translate([0,-2,0]) } {octR}
  
  %put { translate([4,-1, 0]) } {octG}

  %put { scale(2) then translate([4,2,0]) } {octR}
  
  % add some nodes ...
  put {scale(0.1) then translate([0,0,0])} {sphere}
  
  put {scale(0.1) then translate([2,0,0])} {hanging}
  put {scale(0.1) then translate([4,0,0])} {sphere}

  put {scale(0.1) then translate([2,0,2])} {hanging}
  put {scale(0.1) then translate([4,0,4])} {sphere}
  
  put {scale(0.1) then translate([0,0,2])} {hanging}
  put {scale(0.1) then translate([0,0,4])} {sphere}
  
  def bx (2,0,0)
  def by (4,0,0)
  def cx (2,0,2)
  def cy (4,0,4)
  def dx (0,0,2)
  def dy (0,0,4)

  special |\draw [->>] #1 to [bend right=45] #2;|[lay=over](bx)(by)
  special |\draw [->>] #1 to #2;|[lay=over](cx)(cy)
  special |\draw [->>] #1 to [bend left=45] #2;|[lay=over](dx)(dy)



  {axes}
}

put { rotate(-90, (0,0,0), [1,0,0] ) then rotate(45, (0,0,0), [0,1,0] ) then view((10,4,2)) } {octScene}

global { language tikz }

