#!/bin/sh
#PBS -l nodes=24:ppn=2
#PBS -l walltime=30:00
#PBS -j oe
#PBS

numprocs=48
inp=p32M
cmplx=1
incInt=1
runOpt=2
readP=1
readO=0
dim=3
maxD=29
writeP=0
writeO=0
maxNum=1
incCor=1

prefixPath=/opt/openmpi/1.2.4

cd ${DENDRO_DIR}

mpirun -prefix $prefixPath -nooversubscribe -np ${numprocs} ./runScal $inp $cmplx $incInt $runOpt $readP $readO $maxD $writeP $writeO $dim $maxNum $incCor >& ${inp}.${numprocs}.txt

status=$?
exit ${status}

