#!/bin/sh
#PBS -l nodes=1:ppn=2
#PBS -l walltime=10:00
#PBS -j oe
#PBS

numprocs=2
inp=p1K
dim=3
maxD=30
maxNum=1
incCor=1
writeB=0
solveU=0
compressLut=0
numLoops=5

prefixPath=/opt/openmpi/1.2.4

cd ${HOME}/otk

mpirun -prefix $prefixPath -nooversubscribe -np ${numprocs} ./tstMatVec $inp $maxD $solveU $writeB $dim $maxNum $incCor $numLoops ${compressLut} >& oda.${inp}.${numprocs}.txt

status=$?
rm -f ${tmpfile}
exit ${status}



